# Generated by Django 2.0 on 2018-07-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0001_Art_app_initial_db_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='dimension',
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='unit',
            field=models.CharField(default='inch', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
