# Generated by Django 2.0 on 2018-07-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Art', '0002_updated_the_art_model_title_dimension_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now=True)),
                ('artworks', models.ManyToManyField(related_name='artworks', to='Art.Artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArtCollection',
            },
        ),
    ]
