# Generated by Django 2.0 on 2018-08-18 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Art', '0003_added_Artwork_colleciton_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToArtworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Like', 'Like'), ('Save', 'Save')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='Art.Artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_arts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserToArtworkActions',
            },
        ),
    ]
