# Generated by Django 2.0 on 2018-08-18 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Art', '0003_added_Artwork_colleciton_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Inappropriate Content', 'Inappropriate Content'), ('Stolen Property', 'Stolen Property')], default='Pending', max_length=10)),
                ('description', models.TextField(default='', max_length=100)),
                ('reported_on', models.DateField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Art.Artwork')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
    ]
