# Generated by Django 2.0 on 2018-08-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_Initial migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkreport',
            name='report_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Reviewed', 'Reviewed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='artworkreport',
            name='report_type',
            field=models.CharField(choices=[('Inappropriate Content', 'Inappropriate Content'), ('Stolen Property', 'Stolen Property')], default='Stolen Property', max_length=30),
        ),
    ]
