# Generated by Django 2.0 on 2018-08-19 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_added eport status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkreport',
            name='reported_on',
        ),
        migrations.AddField(
            model_name='artworkreport',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artworkreport',
            name='reported_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
