# Generated by Django 2.0 on 2018-08-27 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserFollowWatchApp', '0001_added user to user model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertousermodel',
            name='activity_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Watch', 'Watch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usertousermodel',
            name='base_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertousermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
