# Generated by Django 2.0 on 2018-07-27 06:52

import UserAdministration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_number', models.IntegerField(blank=True)),
                ('street_number', models.IntegerField(blank=True)),
                ('street_name', models.CharField(blank=True, max_length=50)),
                ('neighbourhood', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('province', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_profile_image', models.FileField(blank=True, upload_to=UserAdministration.models.unique_image_path)),
                ('small_profile_image', models.FileField(blank=True, upload_to=UserAdministration.models.unique_image_path)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True, max_length=500)),
                ('website', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('profile_level', models.CharField(choices=[('ProfilePlus', 'ProfilePlus'), ('ProfileLite', 'ProfileLite')], default='ProfilePlus', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='UserAdministration.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
